version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: photo-db
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root973
    command: >
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot973" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: photo-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root973
      DB_NAME: db
    depends_on:
      - db
    volumes:
      - ./public/images:/usr/src/app/public/images

volumes:
  db_data:
